In [1]:
import pandas as pd

Reading Data

In [2]:
df = pd.read_csv('data.csv')

In [24]:
df.head()

        fever  body_pain  age  runny_nose  diff_breath  virus_prob
0   98.483414          1   67           1            1           0
1   98.921034          0   12           0            1           1
2  100.105786          1    7           1            1           1
3   98.543092          1   11           0            1           0
4  100.304603          1   78           1            0           0

In [25]:
df.tail()

           fever  body_pain  age  runny_nose  diff_breath  virus_prob
2838   98.768070          0   72           1           -1           1
2839   99.675222          0   20           1            0           0
2840  101.173407          1   76           0            0           1
2841  100.390725          1   75           1            1           1
2842  100.753574          1   95           0            0           1

In [26]:
df.info() #full info

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2843 entries, 0 to 2842
Data columns (total 6 columns):
fever          2843 non-null float64
body_pain      2843 non-null int64
age            2843 non-null int64
runny_nose     2843 non-null int64
diff_breath    2843 non-null int64
virus_prob     2843 non-null int64
dtypes: float64(1), int64(5)
memory usage: 133.3 KB

In [27]:
df['diff_breath'].value_counts()    #helps to group and take counts (for perticular column)

 1    993
 0    959
-1    891
Name: diff_breath, dtype: int64

In [28]:
df.describe()

,fever,body_pain,age,runny_nose,diff_breath,virus_prob
count,2843.000000,2843.000000,2843.000000,2843.000000,2843.000000,2843.000000
mean,100.002136,0.499472,49.852620,0.502286,0.035878,0.505804
std,1.161131,0.500088,29.014152,0.500083,0.813404,0.500054
min,98.000388,0.000000,1.000000,0.000000,-1.000000,0.000000
25%,99.007745,0.000000,24.000000,0.000000,-1.000000,0.000000
50%,99.985266,0.000000,51.000000,1.000000,0.000000,1.000000
75%,101.020381,1.000000,75.000000,1.000000,1.000000,1.000000
max,101.997358,1.000000,100.000000,1.000000,1.000000,1.000000

Train Test Splitting

In [29]:
import numpy as np

In [30]:
def data_split(data, ratio):
    np.random.seed(42)
    shuffled = np.random.permutation(len(data))
    test_set_size = int(len(data) * ratio)
    test_indices = shuffled[:test_set_size]
    train_indices = shuffled[test_set_size:]
    return data.iloc[train_indices], data.iloc[test_indices]

In [35]:
np.random.permutation(7)

array([5, 4, 2, 6, 1, 0, 3])

In [40]:
train, test = data_split(df, 0.2)

In [41]:
train

           fever  body_pain  age  runny_nose  diff_breath  virus_prob
940   100.292990          0   28           0            1           0
741    98.415072          1    9           1            1           0
2804  100.249023          1   96           0            0           0
2208  101.617279          0   94           0           -1           0
787   101.620851          1   60           0           -1           1
1961  101.751059          0   58           0            0           1
1036  101.439971          1   59           0            1           0
1103   98.804814          0   48           0           -1           1
651   101.074515          1   82           0            0           0
2274   98.500513          0    8           1            0           1
461    99.193010          1   91           1            1           1
2540   99.182173          0   87           0            0           1
157   100.536876          0   92           0            0           1
1739   99.428174          0   42           0            1           0
1511   98.337104          0  100           0            1           0
700    99.780844          1   20           1            0           1
238    99.153792          0   74           1            1           1
2584   99.750281          1   63           0            1           1
1694  100.202446          1   67           1            1           0
2407  101.320812          1   95           1            1           0
100    99.768750          1   60           1           -1           0
315   100.829600          1   10           0            0           1
807    99.855206          0   21           1            1           0
829   100.367772          1   89           0            1           1
612    99.470652          1   95           1            1           0
1410  100.909024          0   53           1           -1           1
261    99.034484          1   51           0            0           1
729    99.461052          0   10           0            0           0
2010   99.069694          0   41           1            0           1
2832  100.501588          0   22           0            1           0
...          ...        ...  ...         ...          ...         ...
2747  100.283507          0   23           1           -1           1
2047  100.087302          1   17           0            1           1
2558   98.621860          1   27           0            1           1
1082  101.150842          0   96           0            0           1
474   100.165662          0   34           0            1           0
747   100.126598          0   87           0            0           1
2300  100.257667          1    1           1            0           0
21    100.479744          1   54           1           -1           1
459    99.592622          1   81           1            1           1
1184   98.391127          0   54           1           -1           1
2324   98.812523          1   49           1            0           0
955   100.277200          0   39           0            1           1
1215   99.509145          0   63           1            0           1
2433   99.084370          1   72           1            0           0
1515   98.165177          0   78           1            1           1
2391  100.831552          1   60           0           -1           1
769    99.837267          0   76           1            0           0
1685  101.792253          0   98           0            0           0
130   100.686226          0   93           1           -1           1
2135   98.663299          1   78           0            1           1
1482   99.233425          1   44           1            1           1
330    99.813754          0   85           0           -1           0
1238   98.123011          0   35           1            1           0
466   100.947548          1   88           0            1           1
2169   99.672025          1   27           0            0           1
1638  100.010738          0    5           0            0           0
1095  101.630692          0   23           0            1           1
1130  101.655875          1   36           0            0           0
1294  101.727712          0   72           0           -1           0
860    99.107186          1    9           0           -1           0

[2275 rows x 6 columns]

In [42]:
test

           fever  body_pain  age  runny_nose  diff_breath  virus_prob
415    98.726536          0   28           0            0           1
2233   98.239363          0   10           1            1           1
1149   99.080468          0   88           1            0           0
1113  100.412025          1   58           0            0           0
1225   98.066021          0   34           0            1           1
354   101.276026          0   26           0            0           1
965    98.163373          1   69           1            1           0
1854   99.590524          1   23           0           -1           1
527   100.123859          0   85           1            1           0
2091   98.040397          1   36           0           -1           0
2186   99.240727          0   69           1           -1           0
1080  100.132946          1   77           1           -1           1
1791   98.035613          0   99           1            0           1
324    98.437222          0    2           0            0           0
677   101.410580          1   90           1            1           0
2298   98.161515          0   72           0           -1           0
2356   98.684941          1   86           1            0           1
794    98.405511          1   71           0            1           1
1364   98.205694          1   90           1            0           0
402    98.082521          0   66           0           -1           1
937   100.479920          1   58           0           -1           0
1995   98.831780          1   49           0            0           1
532    98.430567          0   50           1            0           1
1179   98.885544          1   64           0            1           1
811   101.396475          0   82           0           -1           0
2458  100.039715          0   13           0            0           1
2656  100.815650          1   57           1           -1           1
1670  101.429542          1   32           1            0           1
533   100.529231          0   79           1            0           0
1189  101.207548          0   94           0            0           1
...          ...        ...  ...         ...          ...         ...
1650   99.467266          1   70           0           -1           0
1295   98.036606          1   26           1           -1           0
2462   99.884758          1   78           0            1           1
2743   98.100026          1   87           1           -1           1
2234  101.457650          0   59           0            0           1
2163   98.301361          1   50           0            1           0
2702  101.868566          0   60           0            0           0
542   100.468360          1   42           1            1           1
1135   99.321422          1   34           1            1           1
1586   98.073858          0    2           0           -1           0
755    98.271523          0   31           0            0           0
2029  101.631218          0   52           1            0           0
2316  100.298614          1   44           1            0           0
2739   98.839613          1   31           1            0           0
2744   98.736051          1   93           0            0           0
845    99.910916          0   34           1            1           1
789    98.929527          0   63           1            0           0
1510  100.687082          0   60           1           -1           1
705   101.754005          1   62           1            1           1
435   100.838543          1   97           1            1           0
650    98.703117          1   95           0           -1           1
237   100.638784          0   30           0           -1           0
790   101.662467          0   57           0           -1           0
109   101.426230          1   11           0            1           0
1860   98.343055          1   35           0            1           0
163    99.247245          0   83           0           -1           0
1889   98.952123          1   51           0            1           1
252   100.629721          1   95           0            0           0
1780   98.595010          1   21           1           -1           1
1406   99.024193          0   44           1            0           1

[568 rows x 6 columns]

In [43]:
x_train = train[['fever','body_pain','age','runny_nose','diff_breath']].to_numpy()
x_test = test[['fever','body_pain','age','runny_nose','diff_breath']].to_numpy()

In [44]:
x_train

array([[100.2929902 ,   0.        ,  28.        ,   0.        ,
          1.        ],
       [ 98.41507163,   1.        ,   9.        ,   1.        ,
          1.        ],
       [100.2490226 ,   1.        ,  96.        ,   0.        ,
          0.        ],
       ...,
       [101.6558755 ,   1.        ,  36.        ,   0.        ,
          0.        ],
       [101.7277123 ,   0.        ,  72.        ,   0.        ,
         -1.        ],
       [ 99.10718567,   1.        ,   9.        ,   0.        ,
         -1.        ]])

In [45]:
y_train = train[['virus_prob']].to_numpy().reshape(2275 ,)
y_test = test[['virus_prob']].to_numpy().reshape(568 ,)

In [48]:
y_train

array([0, 0, 0, ..., 0, 0, 0], dtype=int64)

In [47]:
y_test

array([1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1,
       1, 1, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0,
       1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1,
       0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1,
       1, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1,
       1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1, 0,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 1,
       1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 0,
       1, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1,
       1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0,
       0, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 1,
       0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1], dtype=int64)

In [50]:
from sklearn.linear_model import LogisticRegression

In [51]:
clf = LogisticRegression()        # initializing LR model
clf.fit(x_train,y_train)

C:\Users\MuditTripathi\Anaconda3\lib\site-packages\sklearn\linear_model\logistic.py:432: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)

LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='warn', n_jobs=None, penalty='l2',
                   random_state=None, solver='warn', tol=0.0001, verbose=0,
                   warm_start=False)

In [58]:
clf.predict([[100,1,22,1,1]])

array([1], dtype=int64)

In [59]:
input_features = [100,1,22,1,-1]
virus_probability = clf.predict_proba([input_features])[0][1]

In [61]:
virus_probability

0.5273356047068759